### ISSUE TITLE
Battery light

### ISSUE THREAD

**Issue by ShevT** [ResurrectionRemix/Resurrection_packages_apps_Settings#126]
Reproduction:
Settings-> Sound & notification -> Battery light -> Colors -> Battery low
Tap. Press OK. Obtain "Settings has stopped"

logcat:

D/AndroidRuntime(21237): Shutting down VM
E/AndroidRuntime(21237): FATAL EXCEPTION: main
E/AndroidRuntime(21237): Process: com.android.settings, PID: 21237
E/AndroidRuntime(21237): java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.second' on a null object reference
E/AndroidRuntime(21237):        at com.android.settings.notificationlight.LightSettingsDialog.getPulseSpeedOn(LightSettingsDialog.java:251)
E/AndroidRuntime(21237):        at com.android.settings.notificationlight.ApplicationLightPreference$1.onClick(ApplicationLightPreference.java:177)
E/AndroidRuntime(21237):        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
E/AndroidRuntime(21237):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(21237):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(21237):        at android.app.ActivityThread.main(ActivityThread.java:5305)
E/AndroidRuntime(21237):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21237):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(21237):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(21237):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
W/ActivityManager(  498):   Force finishing activity 1 com.android.settings/.SubSettings

**Comment by westcripp** [comment]
this is cm base derp . revert https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/86eb5cc6c7002dc1e23e5295ba9868ad56219453  fixed the issue. thanks

**Comment by ShevT** [comment]
In CM-12.1 this problem is also present.
Thanks!
