### ISSUE TITLE
Settings has stopped

### ISSUE THREAD

**Issue by micky387** [ResurrectionRemix/Resurrection_packages_apps_Settings#146]
Hi. It's again me....
I can now build RR rom with your last commit,thanks.
But now,with fresh install (full wipe) i have setting FC at the start,and If i what to go to setting/Configurations/Miscellaneous,i have Settings has stopped
Do you know about this ??
I will give you logcat if you want.
regards

**Comment by akhilnarang** [comment]
Yes, please run adb logcat | grep "E/"
And give output of it crashing

**Comment by westcripp** [comment]
this is super user issue i think flash superuser zip

**Comment by varund7726** [comment]
Have you flashed super su zip?
BTW plz report bugs on g+ and not here

**Comment by micky387** [comment]
hi all.
@akhilnarang  i will give you logcat today
@westcripp and @varund7726 ,i will try and no flashed super su zip.

**Comment by micky387** [comment]
ok i close issue.
Flashed beta supersu 2.49 and all working now.
i will open rapport on G+ for logcat.
Best regards
