### ISSUE TITLE
Problem with the build

### ISSUE THREAD

**Issue by ShevT** [ResurrectionRemix/Resurrection_packages_apps_Settings#164]
For several days I have a problem with the build for my two devices.
At the same time, the assembly of cyanogen goes well.

Warning: library class org.cyanogenmod.hardware.DisplayModeControl depends on program class cyanogenmod.hardware.DisplayMode
Warning: library class org.cyanogenmod.hardware.DisplayModeControl depends on program class cyanogenmod.hardware.DisplayMode
Warning: library class org.cyanogenmod.hardware.DisplayModeControl depends on program class cyanogenmod.hardware.DisplayMode
Warning: library class org.cyanogenmod.hardware.DisplayModeControl depends on program class cyanogenmod.hardware.DisplayMode
Warning: there were 4 instances of library classes depending on program classes.
         You must avoid such dependencies, since the program classes will
         be processed, while the library classes will remain unchanged.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#dependency)
Error: Please correct the above warnings first.
make: *** [/home/shev/AndroidSources/RR-5.1/master/out/target/common/obj/APPS/Settings_intermediates/proguard.classes.jar] Error 1

**Comment by OmarEinea** [comment]
I was able to build RR 5.5.4, though
I'm having the same problem when I'm trying to build now!

**Comment by ShevT** [comment]
Fixed. Thanks!

**Comment by OmarEinea** [comment]
Same here, thx :)
