### ISSUE TITLE
Can't find strings for "Restart SystemUI" and "Screenrecord"

### ISSUE THREAD

**Issue by TheNoFace** [ResurrectionRemix/Resurrection_packages_apps_Settings#172]
I can't find strings for "Restart SystemUI" and "Screenrecord" on power menu.
I've searched SystemUI strings and custom strings, but it doesn't seem to exist.

**Comment by Jaiglissechef-i9100** [comment]
frameworks/base/packages/SystemUI/res/values/rr_strings.xml line 42 for Restart SystemUI
rameworks/base/core/res/res/values/cm_strings.xml line 28 for Screenrecord

**Comment by TheNoFace** [comment]
@Jaiglissechef-i9100 Oh, I thought screen record would be on rr_strings.xml. However, string "Restart SystemUI" on SystemUI/res/values/rr_strings.xml is for Quicksettings, not power menu. It's already translated but no changes.

**Comment by Jaiglissechef-i9100** [comment]
@TheNoFace Lol, Restart SystemUi is not present in power menu its just present in quicksettings. So i say is true :p

**Comment by TheNoFace** [comment]
@Jaiglissechef-i9100  Um.. Restart SystemUI exists in power menu-reboot when you activate advanced reboot in developer setting. It doesn't seem to be related with CM translations.

**Comment by Jaiglissechef-i9100** [comment]
You confuse hot reboot and restart systemUi but np its ok.

**Comment by TheNoFace** [comment]
Both "Restart SystemUI" and "Screenrecord" were on frameworks/base/core/res/res/values/cm_strings.xml. Thanks for your help.
