### ISSUE TITLE
about phone crash 

### ISSUE THREAD

**Issue by Cr-cm** [ResurrectionRemix/Resurrection_packages_apps_Settings#201]
when touch about phone in settings,it tells settings fc

**Comment by Cr-cm** [comment]
07:44:42.665 Error QCOM PowerHAL 1035  Failed to acquire lock.
07:44:42.667 Error ACDB-LOADER 277  Error: ACDB AudProc vol returned = -19
07:44:42.667 Verbose WindowManager 1035  addAppToken: AppWindowToken{5cb615b token=Token{2cd6986a ActivityRecord{1ba51655 u0 com.android.settings/.SubSettings t22}}} to stack=1 task=22 at 1
07:44:42.667 Error msm8974_platform 277  platform_add_backend_name: Invalid snd_device = 0
07:44:42.667 Error audio_hw_spkr_prot 277  audio_extn_spkr_prot_start_processing: cannot open device '/dev/snd/pcmC0D32c': Invalid argument
07:44:42.667 Error ACDB-LOADER 277  Error: ACDB AudProc vol returned = -19
07:44:42.667 Error msm8974_platform 277  platform_add_backend_name: Invalid snd_device = 0
07:44:42.667 Error audio_hw_primary 277  enable_snd_device: spkr_start_processing failed
07:44:42.790 Error DeviceInfoSettings 4396  package com.cyanogenmod.updater not installed, hiding preference.
07:44:42.790 Error AndroidRuntime 4396  FATAL EXCEPTION: main
07:44:42.790 Error AndroidRuntime 4396  Process: com.android.settings, PID: 4396
07:44:42.790 Error AndroidRuntime 4396  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.onPrepareForRemoval()' on a null object reference
07:44:42.790 Error AndroidRuntime 4396  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2431)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.ActivityThread.access$900(ActivityThread.java:154)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
07:44:42.790 Error AndroidRuntime 4396  	at android.os.Handler.dispatchMessage(Handler.java:102)
07:44:42.790 Error AndroidRuntime 4396  	at android.os.Looper.loop(Looper.java:135)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.ActivityThread.main(ActivityThread.java:5309)
07:44:42.790 Error AndroidRuntime 4396  	at java.lang.reflect.Method.invoke(Native Method)
07:44:42.790 Error AndroidRuntime 4396  	at java.lang.reflect.Method.invoke(Method.java:372)
07:44:42.790 Error AndroidRuntime 4396  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
07:44:42.790 Error AndroidRuntime 4396  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
07:44:42.790 Error AndroidRuntime 4396  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.onPrepareForRemoval()' on a null object reference
07:44:42.790 Error AndroidRuntime 4396  	at android.preference.PreferenceGroup.removePreferenceInt(PreferenceGroup.java:192)
07:44:42.790 Error AndroidRuntime 4396  	at android.preference.PreferenceGroup.removePreference(PreferenceGroup.java:185)
07:44:42.790 Error AndroidRuntime 4396  	at com.android.settings.DeviceInfoSettings.onCreate(DeviceInfoSettings.java:214)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.Fragment.performCreate(Fragment.java:2031)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.BackStackRecord.run(BackStackRecord.java:834)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:483)
07:44:42.790 Error AndroidRuntime 4396  	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:1008)
07:44:42.790 Error AndroidRuntime 4396  	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:611)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.Activity.performCreate(Activity.java:6865)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
07:44:42.790 Error AndroidRuntime 4396  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2322)
07:44:42.790 Error AndroidRuntime 4396  	... 10 more
07:44:43.306 Error QCOM PowerHAL 1035  Failed to acquire lock.
07:44:44.795 Verbose ActivityManager 1035  killProcessGroupAsync took 31 ms for PID 4396 on thread 17

**Comment by varund7726** [comment]
huh?
how did this happen?
no such crash here
which device?

**Comment by Cr-cm** [comment]
cancro ,i build for xiaomi 4
