### ISSUE TITLE
Crash settings

### ISSUE THREAD

**Issue by ShevT** [ResurrectionRemix/Resurrection_packages_apps_Settings#278]
Lollipop5.1 branch:

Settings -> More

D/AndroidRuntime(21501): Shutting down VM
E/AndroidRuntime(21501): FATAL EXCEPTION: main
E/AndroidRuntime(21501): Process: com.android.settings, PID: 21501
E/AndroidRuntime(21501): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.onPrepareForRemoval()' on a null object reference
E/AndroidRuntime(21501): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370)
E/AndroidRuntime(21501): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2432)
E/AndroidRuntime(21501): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime(21501): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime(21501): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(21501): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(21501): 	at android.app.ActivityThread.main(ActivityThread.java:5310)
E/AndroidRuntime(21501): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21501): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(21501): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(21501): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(21501): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.onPrepareForRemoval()' on a null object reference
E/AndroidRuntime(21501): 	at android.preference.PreferenceGroup.removePreferenceInt(PreferenceGroup.java:192)
E/AndroidRuntime(21501): 	at android.preference.PreferenceGroup.removePreference(PreferenceGroup.java:185)
E/AndroidRuntime(21501): 	at com.android.settings.WirelessSettings.onCreate(WirelessSettings.java:337)
E/AndroidRuntime(21501): 	at android.app.Fragment.performCreate(Fragment.java:2031)
E/AndroidRuntime(21501): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863)
E/AndroidRuntime(21501): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
E/AndroidRuntime(21501): 	at android.app.BackStackRecord.run(BackStackRecord.java:834)
E/AndroidRuntime(21501): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
E/AndroidRuntime(21501): 	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:483)
E/AndroidRuntime(21501): 	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:1008)
E/AndroidRuntime(21501): 	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:611)
E/AndroidRuntime(21501): 	at android.app.Activity.performCreate(Activity.java:6865)
E/AndroidRuntime(21501): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(21501): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2323)
E/AndroidRuntime(21501): 	... 10 more
W/ActivityManager(  488):   Force finishing activity 1 com.android.settings/.SubSettings
W/ActivityManager(  488):   Force finishing activity 2 com.android.settings/.Settings

**Comment by varund7726** [comment]
Cant reproduce this .sorry

**Comment by akhilnarang** [comment]
@shevT is it a non NFC device?

**Comment by varund7726** [comment]
akhil if possible revert that nfc commit
cm derping again i think

**Comment by ShevT** [comment]
>> Cant reproduce this .sorry
I reproduce on a "clean" installation.

>> @shevT is it a non NFC device?
My devices does not have NFC.

**Comment by varund7726** [comment]
@shevT just merged a fix.can you test?

**Comment by ShevT** [comment]
I tested. Everything is fine. Settings do not crash.
But NFC settings remain. http://imagebin.ca/v/2Log3COJ7x2e
Can they be removed?

**Comment by varund7726** [comment]
Its an unusable option right? I think this is the only workaround to fix FC
Till I find another solution

**Comment by akhilnarang** [comment]
Or revert the fix, revert CMs commit that causes fc

**Comment by ShevT** [comment]
Something must be done.
Users complain about the unnecessary options. 
And I do not need them, if there is no NFC.
I will wait for the decision.

**Comment by varund7726** [comment]
I don't understand what's there to complain about? Its not like its eating their ram or resources

**Comment by ShevT** [comment]
This extra menu items that are not needed.

**Comment by akhilnarang** [comment]
Revert the fix, revert CMs commit. And let us know what happens then

**Comment by varund7726** [comment]
Yes you will have yo revert every time you build
Because its a cm change and if we revert it , it will cause issues for majority devices

**Comment by ShevT** [comment]
Then we leave.
Thank you!
