### ISSUE TITLE
Add me as Motorola Moto Maxx "Quark" Maintainer

### ISSUE THREAD

**Issue by bhb27** [ResurrectionRemix/Resurrection_packages_apps_Settings#281]
Regards this

https://gist.github.com/westcripp/d857dbe6f9f1b98b74f7

I don't use social network. I try XDA PM but no luck.

http://forum.xda-developers.com/moto-maxx/development/rom-resurrection-remix-5-5-5-t3197643

Thanks.

**Comment by akhilnarang** [comment]
make a pull request to add it please

**Comment by bhb27** [comment]
Done.

Thank you.

**Comment by varund7726** [comment]
Why did you pm westcrip .in the miantainer section its clearly mentioned you should pm me for maintainers

**Comment by bhb27** [comment]
Is not clear, at least for me it is not. "Send a PM to Shubhang (xenon92) or Altan (westcrip) at XDA" doesn't says to PM you any were.

The only maintainers section I have access is this link

https://gist.github.com/westcripp/d857dbe6f9f1b98b74f7

Maybe there is other in some forum or social network, i did not find... But anyway it's all ok.

Thanks.

**Comment by akhilnarang** [comment]
About phone > about resurrection > devices and maintainers

**Comment by bhb27** [comment]
Yes, is there, don't really ever read that and I don't use hangout. Maybe update that link i posted, or open a wiki on this git will help...

Thanks...

**Comment by akhilnarang** [comment]
Lol, that's where you name is going, you should read it
