### ISSUE TITLE
About a phone CPU?

### ISSUE THREAD

**Issue by bhb27** [ResurrectionRemix/Resurrection_packages_apps_Settings#368]
My about a phone CPU show 0 (zero), but it is a 4 core krait
And RAM 2777. I wanna to show 3072

[this pic](https://dl.dropboxusercontent.com/u/281742759/rr/m/Screenshot_20160216-235132.png)

I wanna or remove this or add the right value, but I look to the code and I don't get it

I check and the commit for this seems to be this one...

https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/6120ddcd9896f0bf1dbc5e82338e6b807a9af98e

I look to many RR device tree I don't see any to set the values there I check boardconfig.mk, device.mk, overlay and system.prop

I try to search on base did find a thing...

Can this be overlay to a choosing value? 
Or can this be removed?

Thanks.

**Comment by varund7726** [comment]
which device is this?

**Comment by varund7726** [comment]
![screenshot_20160217-115734](https://cloud.githubusercontent.com/assets/5579562/13101563/b91ad22a-d56d-11e5-9d68-9c2870ad3da7.png)


No such problem here

**Comment by bhb27** [comment]
Is Moto maxx.

this device tree
https://github.com/bhb27/android_device_motorola_quark/tree/RR-2M

**Comment by varund7726** [comment]
how much ram does it show in recents membar>?

**Comment by bhb27** [comment]
It show free RAM... 1639MB

**Comment by varund7726** [comment]
can you download https://play.google.com/store/apps/details?id=com.dama.hardwareinfo 

and tell me how much ram its showing?

**Comment by bhb27** [comment]
![screenshot_20160217-092628](https://cloud.githubusercontent.com/assets/13755892/13108206/cfd3c6b2-d558-11e5-9b39-fdd34fbe918d.png)

**Comment by varund7726** [comment]
See memory is 2777 MB
so how can you change it to 3072?

2777 is the correct value for RAM

**Comment by bhb27** [comment]
I know to system but the hardware it is 3072MB, can't be 2777MB.
I don't mind about that. the CPU I wanna to fix or remove.
If remove is a option I can use that...

can I?

**Comment by varund7726** [comment]
you cant remove 
i have no idea why its showing 0 for CPU
but it will never show hardware values ( 3072 MB ) 

2777 is the value set by your kernel and you cannot change it
3072 is just a theoretical value and the actualy value is 2777

**Comment by bhb27** [comment]
Ok.

the odd thing is my device and your device from the pic have the same CPU processor...

With tree is that? from the device of your pic
I will cross check things to see if I can find any thing on the .mk file's that is different...

**Comment by varund7726** [comment]
https://github.com/ResurrectionRemix-Devices/android_device_oneplus_bacon

**Comment by bhb27** [comment]
Thanks.

Leave this open please, I post a solution if I find one... If not I close in a few days...

**Comment by varund7726** [comment]
no problem

**Comment by bhb27** [comment]
"I fix it"

The problem is not a problem, is just my /proc/cpuinfo that is different and must be other devices just like mine...

To fix I just change lines

https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/blob/marshmallow/src/com/android/settings/DeviceInfoSettings.java#L585

and

https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/blob/marshmallow/src/com/android/settings/DeviceInfoSettings.java#L603

Replace the result... for... result =  "wherever I wanna";
I know this is not a fix but it is for me.

I don't know java to make a fix, but is possible to just make a "if" on the CPU part to if result == 0 on the first run, do a code to get second line of /proc/cpuinfo

![screenshot_20160219-160521](https://cloud.githubusercontent.com/assets/13755892/13184597/009d7780-d724-11e5-9c99-856bae0e8c09.png)

![screenshot_20160219-111252](https://cloud.githubusercontent.com/assets/13755892/13184607/0776db28-d724-11e5-814a-f6eb9e71852f.png)
