### ISSUE TITLE
Might have broken color picker menu

### ISSUE THREAD

**Issue by Dutchman1990** [ResurrectionRemix/Resurrection_packages_apps_Settings#371]
Color picker menu is giving FC for clock, date and everything else with color changing ability.

**Comment by varund7726** [comment]
This is only for tablet right? Please grab  a log

**Comment by Dutchman1990** [comment]
Yup. Sorry for the inconvenience, I'll pull a log and post the link here.

**Comment by Dutchman1990** [comment]
[grouper_rr.txt](https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/files/145933/grouper_rr.txt)
Log

**Comment by varund7726** [comment]
Fixed
