### ISSUE TITLE
Hardware keys not disabled when using softnav buttons.

### ISSUE THREAD

**Issue by lunsarn** [ResurrectionRemix/Resurrection_packages_apps_Settings#381]
It worked before when using the previous ButtonSettings.java. Is there something I'm missing or do I need to add something new to the device specific tree perhaps? Any help appreciated :)

The device I'm building for is OnePlus X Onyx

**Comment by varund7726** [comment]
Yes .I had mentioned on the g+ group .did you not see it? It was a pinned post many days back

**Comment by lunsarn** [comment]
Nope I didn't. Sorry to bug you man, I'm new to github and building roms, but I'm learning quickly :)

**Comment by varund7726** [comment]
https://plus.google.com/+varund7726/posts/4sXe2F5DjiQ

**Comment by lunsarn** [comment]
Thank you very much!

**Comment by varund7726** [comment]
No problem :)
