### ISSUE TITLE
Profiles 3g/2g/lte switch

### ISSUE THREAD

**Issue by regalstreak** [ResurrectionRemix/Resurrection_packages_apps_Settings#423]
Is it a bug or im facing this issue?
I cannot find the 2g/3g/lte switch in profiles.
Please report @akhilnarang @varund7726 @westcripp 
Do we need an overlay for that ?

**Comment by varund7726** [comment]
Its the same as CM 
we havent touched profiles

**Comment by josarmand0** [comment]
Download the 4g app from the store
