### ISSUE TITLE
Devixe maintainee

### ISSUE THREAD

**Issue by regalstreak** [ResurrectionRemix/Resurrection_packages_apps_Settings#448]
@akhilnarang @varund7762
Reason for this? A link or something?

Commit 0f638b6967 on ResurrectionRemix/Resurrection_packages_apps_Settings
https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/0f638b696778ed2134672342e52dbc26e48129a5

**Comment by varund7726** [comment]
You both can post your own builds  .his name has just been added because he uses our basketbuild to host builds while you use your own account :)
