### ISSUE TITLE
Error during building Settings app

### ISSUE THREAD

**Issue by iArti** [ResurrectionRemix/Resurrection_packages_apps_Settings#610]
I'm building RR for Samsung vivalto3gvn (Ace 4 Lite) and I got this error during compilation of Setting app:
`packages/apps/Settings/res/values/rr_arrays.xml:436: error: Error: No resource found that matches the given name (at '^index_0' with value '@*android:drawable/ic_shortcut_alarm').

nothing matches overlay file activities_icon.png, for flavor `
How can I fix it?

**Comment by varund7726** [comment]
That's not the error.repo sync and build and it will be fixed

**Comment by westcripp** [comment]
@iArti  this is just a warn . not a error . relax

**Comment by iArti** [comment]
No, that's error
I got after that
'#### make failed to build some targets (51:31:46 (hh:mm:ss)) ####'
Okay, I try to sync again

**Comment by iArti** [comment]
Synced. Still the same

**Comment by iArti** [comment]
Just synced, still the same error

**Comment by iArti** [comment]
Sorry for double
I even tried to put sources manually, error again
