### ISSUE TITLE
Where's the nougat branch?

### ISSUE THREAD

**Issue by github-cygwin** [ResurrectionRemix/Resurrection_packages_apps_Settings#629]
Hi,

a couple of days ago I repo sync'ed RR to build 5.8, but didn't manage to actually
build.  Today I tried to repo sync again and for some reason the nougat branch of
Resurrection_packages_apps_Settings is not available and the repo sync fails:

fatal: Couldn't find remote ref refs/heads/nougat

Was the nougat branch removed by accident or did I miss something? What do I
have to do to get back on track?

Thanks,
Corinna

**Comment by varund7726** [comment]
We are experiencing technical difficulties so we have gone private for a while .we will go open source again as soon as issues are resolved 
Thanks
