### ISSUE TITLE
Position of fingerprint scanner in help screen is off

### ISSUE THREAD

**Issue by github-cygwin** [ResurrectionRemix/Resurrection_packages_apps_Settings#661]
Hi,

I'm helping porting LineageOS 14.1 and RR 5.8.0 to kccat6 (Samsung Galaxy S5 LTE+, G901F).  The device has the same layout as the klte, the sensor is in the home button.  On both devices I observe a problem in terms of showing the user where to find the fingerprint sensor, which does not occur in RR 5.7.4.

The settings for both devices are
```
    <integer name="config_fingerprintSensorLocation">1</integer>
    <dimen name="fingerprint_dot_radius">5dp</dimen>
    <item name="fingerprint_sensor_location_fraction_y" type="fraction">94.68%</
```

The fingerprint help screen shows a small picture of a stylised mobile device.  When viewing the help screen in landscape mode, the small dot representing the position of the fingerprint scanner shows up exactly where it should, in the middle of the bottom bezel of the stylised device on the screen.

However, when viewing the help screen in portrait mode, the fingerprint dot is not at the position in the bezel of the small device picture.  Rather you'll find it at the bottom of the actual physical screen, right above the actual physical home button.
It is as if in portrait mode, the height value used for the position computation is accidentally  the actual vertical size of the device screen (1920px) rather than the dimension of the stylised device picture on the screen.

Did I explain the problem sufficiently?  If not, I can try to provide a screenshot showing the
small dot representing the sensor in the wrong spot.  I'd love to provide a patch but my java is lacking :}

Thanks,
Corinna

**Comment by varund7726** [comment]
Please report issues on our g+ page .thanks

**Comment by github-cygwin** [comment]
Sigh, I think I'm too old for this social media stuff.

As I said, I'm trying to port kccat6 to LinOS and RR, the XDA threads are
https://forum.xda-developers.com/galaxy-s5/development/rom-lineage-os-samsung-galaxy-s5-lte-t3534283/ and
https://forum.xda-developers.com/galaxy-s5/development/rom-resurrection-remix-samsung-galaxy-t3534296

I tried to wrap my head around this confusing google+ web site, but I don't understand where bug reports like these are supposed to go, nor did I even see a way to post *any* kind of comment in the RR google+ community.  Is there no bug reporting system like bugzilla or something like that?

Please help.

Corinna

**Comment by github-cygwin** [comment]
Never mind, I posted this issue now under the "Discussion / Issues" section.  Hope that was right...

Corinna
