### ISSUE TITLE
Fingerprint settings crashes when leaving and reentering enrollment screen

### ISSUE THREAD

**Issue by github-cygwin** [ResurrectionRemix/Resurrection_packages_apps_Settings#662]
Hi,

another problem with the fingerprint settings on RR 5.8.0.

Assuming you have no fingerprint stored.  On entering the fingerprint enrollment settings, you get the base info screen first.  Next is the authentication screen, then the "find sensor" screen,
then the fingerprint enrollment screen.
If I leave this screen without entering fingerprint data, then reenter the enrollment screen, Settings crashes.

I attached a logcat of the aforementioned described situation.

[fp-log.txt](https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/files/705147/fp-log.txt)

Hope that helps,
Corinna

**Comment by varund7726** [comment]
Please report issues on our g+ page
