### ISSUE TITLE
Galaxy S7 maintainer "gwolf2u" just kanged his RR-Port from another Dev-Team

### ISSUE THREAD

**Issue by Nestade** [ResurrectionRemix/Resurrection_packages_apps_Settings#726]
Hello,

https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/pull/724

The maintainer gwolf2u kanged his release from the following Dev-Team:
S7e/S7-Head-maintainer: https://forum.xda-developers.com/member.php?u=6371894
XDA-Thread: https://forum.xda-developers.com/s7-edge/development/rom-resurrection-remix-os-nougat-t3528861
Github: https://github.com/8890dev
DL-Page (including RR for S7 and S7e): http://download.jesec.io/
Build-Server: https://ci.jesec.io/

As you can see it's exactly the same ROM as gwolf2u's - but Jesse and his team are the real maintainers.
They were the first ones porting AOSP to the S7e and S7 and then they started with their RR-Port-project.

gwolf2u didn't ask any of them for permissions - he just kanged the SRC and applied here for Official with other ppls work.

Regards,
Nestade

**Comment by SscSPs** [comment]
I don't know what's going on, but there's a possibility that they asked him to take the maintainership
