### ISSUE TITLE
Switching to another keyboard

### ISSUE THREAD

**Issue by ShevT** [ResurrectionRemix/Resurrection_packages_apps_Settings#96]
I do not know where to write. I will write here.
It has long been watching the following issue on my tablet: When you try to select the input method get the error "Unfortunately, Settings has stopped". On my phone, this error does not reproduce.

How to reproduce: Settings -> Language & input -> Current keyboard -> CHOOSE KEYBOARDS

in logcat:
I/ActivityManager( 2771): START u0 {act=android.settings.INPUT_METHOD_SETTINGS flg=0x14200000 cmp=com.android.settings/.Settings$InputMethodAndLanguageSettingsActivity} from uid 1000 on display 0
V/WindowManager( 2771): addAppToken: AppWindowToken{1ff0dcb7 token=Token{1359b7b6 ActivityRecord{31073351 u0 com.android.settings/.Settings$InputMethodAndLanguageSettingsActivity t9}}} to stack=1 task=9 at 2
D/OpenGLRenderer( 2771): endAllStagingAnimators on 0xa0509e80 (RippleDrawable) with handle 0x9f838980
D/AndroidRuntime( 9813): Shutting down VM
E/AndroidRuntime( 9813): FATAL EXCEPTION: main
E/AndroidRuntime( 9813): Process: com.android.settings, PID: 9813
E/AndroidRuntime( 9813): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.Settings$InputMethodAndLanguageSettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.onPrepareForRemoval()' on a null object reference
E/AndroidRuntime( 9813):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
E/AndroidRuntime( 9813):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2421)
E/AndroidRuntime( 9813):        at android.app.ActivityThread.access$900(ActivityThread.java:153)
E/AndroidRuntime( 9813):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
E/AndroidRuntime( 9813):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9813):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 9813):        at android.app.ActivityThread.main(ActivityThread.java:5347)
E/AndroidRuntime( 9813):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9813):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 9813):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 9813):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 9813): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.onPrepareForRemoval()' on a null object reference
E/AndroidRuntime( 9813):        at android.preference.PreferenceGroup.removePreferenceInt(PreferenceGroup.java:192)
E/AndroidRuntime( 9813):        at android.preference.PreferenceGroup.removePreference(PreferenceGroup.java:185)
E/AndroidRuntime( 9813):        at com.android.settings.inputmethod.InputMethodAndLanguageSettings.onCreate(InputMethodAndLanguageSettings.java:244)
E/AndroidRuntime( 9813):        at android.app.Fragment.performCreate(Fragment.java:2031)
E/AndroidRuntime( 9813):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863)
E/AndroidRuntime( 9813):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
E/AndroidRuntime( 9813):        at android.app.BackStackRecord.run(BackStackRecord.java:834)
E/AndroidRuntime( 9813):        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
E/AndroidRuntime( 9813):        at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:483)
E/AndroidRuntime( 9813):        at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:1005)
E/AndroidRuntime( 9813):        at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:608)
E/AndroidRuntime( 9813):        at android.app.Activity.performCreate(Activity.java:5995)
E/AndroidRuntime( 9813):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 9813):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2312)
E/AndroidRuntime( 9813):        ... 10 more
W/ActivityManager( 2771):   Force finishing activity 1 com.android.settings/.Settings$InputMethodAndLanguageSettingsActivity
W/ActivityManager( 2771):   Force finishing activity 2 com.android.settings/.SubSettings

I beg you - correct. I can not use another keyboard.

**Comment by westcripp** [comment]
Thank you for report . I ll look in to

**Comment by akhilnarang** [comment]
Which tablet???
I think this was an issue on an old version of RR, fixed a while ago....

**Comment by ShevT** [comment]
Tablet - Samsung Galaxy Note 10.1 (2014)
devtree - https://github.com/ShevT/device_samsung_lt033g
In Cyanogenmod - this is no problem

**Comment by ShevT** [comment]
Checked. The problem is fixed. Thank you!

**Comment by bronx3000** [comment]
i have the same problem. my device is a samsung galaxy s2
